os: osx
osx_image: xcode10.1

language: cpp

addons:
  homebrew:
    packages:
      - ccache

cache:
  # large cache requires large timeout for transfer
  timeout: 1800
  ccache: true
  directories:
    - ./v8build

jobs:
  include:
    - stage: fetch-v8
      script: ./fetch-v8.sh
    - stage: build-antlr4-icu-torque
      script: ./build.sh antlr4 icu torque
    - stage: build-v8-libbase-libplatform-libsampler-base
      script: ./build.sh v8_libbase v8_libplatform v8_libsampler v8_base
    - stage: build-d8-v8
      script: ./build.sh d8 v8
