os: osx
osx_image: xcode10.1

addons:
  homebrew:
    packages:
      - ccache

cache: ccache

jobs:
  include:
    - stage: "Build icu"
      script: ./build.sh icu
    - stage: "Build d8, v8"
      script: ./build.sh d8 v8
