os: osx
osx_image: xcode10.1

language: cpp

addons:
  homebrew:
    packages:
      - ccache

cache:
  ccache: true
  directories:
    - ./v8build

jobs:
  include:
    - stage: "Build icu"
      script: ./build.sh icu
    - stage: "Build d8, v8"
      script: ./build.sh d8 v8
