os: osx
osx_image: xcode10.1

language: cpp

addons:
  homebrew:
    packages:
      - ccache

cache:
  # large cache requires large timeout for transfer
  timeout: 1800
  ccache: true
  directories:
    - ./v8build

jobs:
  include:
    - stage: fetch-v8
      script: ./fetch-v8.sh
    - stage: build-v8-stage-1
      script: ./build.sh antlr4 icu inspector torque v8_libbase v8_libplatform v8_libsampler
    - stage: build-v8-stage-2
      script: ./build.sh v8_base
    - stage: build-v8-stage-3
      script: ./build.sh d8 v8
