os: osx
osx_image: xcode10.1

language: cpp

addons:
  homebrew:
    packages:
      - ccache

cache:
  ccache: true
  directories:
    - ./v8build

jobs:
  include:
    - stage: fetch-v8
      script: ./fetch-v8.sh
    - stage: build-antlr4
      script: ./build.sh antlr4
    - stage: build-icu
      script: ./build.sh icu
    - stage: build-v8
      script: ./build.sh d8 v8
